- README.md
- package-lock.json
- package.json
- svelte.config.js
commit fa663fe4fec08bd007cda202e93ee210a22a5d3d (HEAD -> feature/build-node-and-netlify, origin/feature/build-node-and-netlify)
Date:   Wed Mar 16 20:20:25 2022 +0000
build with different adapters according to SKADAPTER env var
- add switch to svelte.config.js that checks env for variable
SKADAPTER.
- if SKADAPTER='node', 'npm run build' will run with a node adapter
- if SKADAPTER is anything else (or unset), 'npm run build' will
run with automatic adapter
- added npm build-node script that sets SKADAPTER='node' and then
builds.
These changes needed to allow env-specific builds (netlify for dev,
node for prod).
Make sure the netlify deploy worked ok - no home for node yet
anyone
> optional node build

- src/data/fetchGeographyData.ts
- src/helpers/categoryHelpers.ts
- src/helpers/spatialHelper.ts
commit 195a67f98de9cad7b05c680d857870a252e4fba2 (HEAD -> fix/category-heading-no-category-data, origin/fix/category-heading-no-category-data)
Date:   Wed Mar 23 16:02:35 2022 +0000
Stop asking geo endpoint for england and wales data (not available)
Refactor fetchGeographyData.fetchGeographyLookup to return
spatialHelper.defaultGeography (England and Wales) if asked for
something that matches, RATHER than ask the API for it.
This change needed as the back end does not hold geometry data for
England and Wales.
Read the code etc, check preview can handle having England and Wales in the selected geography store
Anyone
> Stop asking geo endpoint for england and wales data (not available)

- src/routes/health.ts
Add simple /health endpoint returning 200 + basic JSON. This
change needed to allow ONS CI (nomad) to monitor deployment
health.
run app and chec the /health route
Anyone
> /heath endpoint for ONS CI heartbeat monitoring

- dp-census-atlas.nomad
nomad file was using default go-binary-starting command (./dp-census-atlas) but this is a node project, so needs a node start command.
> use correct app start args for nomad

- package-lock.json
- package.json
- src/components/CategoryPage.svelte
- src/data/api.ts
- src/data/setVizStore.ts
- src/helpers/spatialHelper.ts
- src/helpers/spatialHelper.ts.test.ts
- src/map/initMap.ts
- src/types.ts
commit 3d2cfc598e0b7c9768edda8ff7d1c9177443a2f4 (HEAD -> feature/snap-bbox-requests-to-map-tile, origin/feature/snap-bbox-requests-to-map-tile)
Date:   Tue May 10 12:05:54 2022 +0100
spatialHelpers.getQuantisedBbox snaps viewport bbox to slippy max x,y
snapBboxToMapGrid takes viewport bbox and snaps corners to nearest
slippy map x, y points for current zoom level (rounded down to nearest
integer value).
These changes needed to reduce variability in bbox requests made to
the api, in order to better make use of request-keyed serverside cache.
run tests with `npm run test`
Run locally, check it works
Anyone
> Feature/snap bbox requests to slippy map x,y

- src/components/CategoryPage.svelte
- src/data/api.ts
- src/data/api.ts.test.ts
- src/data/setVizStore.ts
- src/helpers/spatialHelper.ts
refactor api.ts functions (nb module probably wants renaming!)
to pull data from s3 flat files (for census map data and
census data breaks) as well as API (for geo info and selected
geography data). This change needed as PoC for shift to
flat-file for everything.
> load census data + breaks from s3 flat files rather than api

- src/components/Layout.svelte
Remove call to fetchSelectedGeographyData made on import / load
of layout.svelte, as:
-  this was running on the server (where the API is not always
available) and was breaking CI
- the UI elements informed by fetchSelectedGeographyData are being
deprecated
Remove call to fetchSelectedGeographyData made on import / load
of layout.svelte, as:
-  this was running on the server (where the API is not always
available) and was breaking CI
- the UI elements informed by fetchSelectedGeographyData are being
deprecated
read the code
Anyone
> remove on-load call to fetchSelectedGeographyData in layout.svelte

- src/components/Layout.svelte
- src/data/api.ts
Replace remaining API-calling functions for currently selected
geography with mock functions that return dummy data (UI is in-flux
at the moment and so can't be changed too much, so idea here is
to remove the API completely without making changes to the UI + routes)
This is temporary - the API and the UI that depends on it should
be removed as soon as possible.
> mock out API calls out to preserve UI

- src/data/api.ts
- src/data/setVizStore.ts
- src/helpers/mapKeyHelper.ts
- src/map/renderMapViz.ts
- src/types.ts
Consume ratioToTotal census data directly from csv files
rather than calculate as census data value / total for each
geography.
These changes needed to minimise csv file size
> consume ratioToTotal census data direct from flat files

- ci/scripts/unit.sh
commit 2c603b94927084be18e48df1827cc344a03077ca (HEAD -> bugfix/fix-ci-unit-tests, origin/bugfix/fix-ci-unit-tests)
Date:   Fri Jul 29 10:45:54 2022 +0100
replace build with build:sandbox in ci unit test script
> remove redundant (and broken) build stage from ci unit test script

- env/dev.sh
- env/netlify.sh
- env/sandbox.sh
- src/data/api.ts
commit 2ddc0f9383dbcbd58490524cb6a098c54e3e32f3 (HEAD -> feat/add-tiles-nesting-to-data-requests, origin/feat/add-tiles-nesting-to-data-requests)
Date:   Wed Aug 31 09:23:58 2022 +0100
add tiles subpath to requests for data tiles
- change s3 base url to 'newquads' test data tile set
- add new 'tiles' sub-path to requests for data tiles
Road-test the netlify preview and see if anything is broken when getting files from the new S3 path.
Anyone
> add tiles subpath to requests for data tiles

- src/data/setContentStores.ts
- src/routes/runtime-env.ts
fix runtime-env ep calls from setContentStores on census-atlas basepath
- Fix bug where setContentStores calls to runtime-env endpoint where not accounting for app base paths other than "".
- Remove reundant params arg from runtime-env endpoint request handler func.
> fix runtime-env ep calls from setContentStores on census-atlas basepath

- src/data/content.ts
add (empty) entries for `staging` and `prod` environments to content.ts. This change needed to deploy the atlas to these environments and have it display the service unavailable page.
read the code
Anyone
> add content.ts keys for staging and prod

- dp-census-atlas.nomad
- env/ons.sh
- workaround-sveltekit-3726.sh
NB not to merge until related front-end router changes are made! (https://github.com/ONSdigital/dp-frontend-router/pull/346)
commit 04d5bd12495150418dc545c941cc8d5f20d49beb (HEAD -> feat/new-basepath-maps/census, origin/feat/new-basepath-maps/census)
Date:   Fri Sep 16 09:41:25 2022 +0100
parameterise app base path in workaround-sveltekit-3726.sh
commit 85f48ae577fc97a7cec05009d72d719047bc1e75
Date:   Fri Sep 16 08:40:21 2022 +0100
appBasePath -> /census/maps for ONS deployments
read the changes
Anyone
> appBasePath -> /census/maps for ONS deployments

- content/legend_strs_to_csv.py
- content/split_content_by_topic.py
New script added to content dir, split_content_by_topic.py splits a content.json file into multiple files based on variable.topic_code. This change needed as releases are done by topic, and therefore each release will need a topic-specific content.json file.
> content.split_content_by_topic.py splits content json by topic_code

- vite.config.ts
commit 61bb2eeb6fe09c062e84b6b964621b0282f0c5f2 (HEAD -> feat/revert-local-port-to-28100, origin/feat/revert-local-port-to-28100)
Date:   Thu Oct 6 08:43:27 2022 +0100
local port 28100 to avoid clashes with other ONS apps
> local port 28100 to avoid clashes with other ONS apps

- src/components/BreaksChart.svelte
- src/components/MapLegend.svelte
- src/data/api.ts
- src/helpers/ratioHelpers.ts
- src/util/numberUtil.ts
- src/util/numberUtils.ts.test.ts
commit 35e8c36a5c9a06850aaac86c6712b1ddf2a491ef (HEAD -> feat/0.1%-max-precision-in-ui, origin/feat/0.1%-max-precision-in-ui)
Date:   Fri Oct 7 11:27:32 2022 +0100
add ratioHelpers as source-of-truth for rounding ratios
- ratioHelpers.ts exports functions that round ratios and percentages
to a configurable number of decimal places for display. This avoids
having the number of decimal places set in several different places.
- api.ts, BreaksChart.svelte and MapLegend.svetle refactored to
use functions from ratioHelpers.ts
commit 87885a0e3281ad45181e0270e69e4047ebc8d9ce
Date:   Fri Oct 7 11:09:39 2022 +0100
round breaks to 3 decimal places (=1 % decimal place) and remove duplicates
- …
> Feat/0.1% max precision in UI

- src/components/BreaksChart.svelte
- src/components/MapLegend.svelte
- src/data/api.ts
- src/helpers/percentageHelpers.ts
- src/helpers/ratioHelpers.ts
commit b9b9f0c5e5cc153617f5c3308e4bf6bd8a307a77 (HEAD -> feature/handle-ratio-and-percentage-data, origin/feature/handle-ratio-and-percentage-data)
Date:   Mon Oct 24 14:52:03 2022 +0100
replace ratioHelpers with percentageHelpers as prod data in %
- new module percentageHelpers.ts does equivalent processing /
rouding to ratioHelpers.ts but for % (i.e. one decimal place
instead of three, don't mutltiply by 100 for display)
- ratioHelpers.ts swapped out for percentageHelpers.ts throughout
code (this is stopgap while fake data is still in ratios -
ratioHelper can be swapped in locally to test out changes)
> replace ratioHelpers with percentageHelpers as prod data in %

- src/components/BreaksChart.svelte
- src/components/MapLegend.svelte
- src/data/api.ts
- src/data/content.ts
- src/map/renderMapViz.ts
- src/stores/viz.ts
- src/types.ts
commit 760586e86ead9b19ea5c1e33eef3a50ab2720b10 (HEAD -> fix/scale-bar-wrong-colors-when-reduced-n-breaks, origin/fix/scale-bar-wrong-colors-when-reduced-n-breaks)
Date:   Wed Nov 2 11:34:37 2022 +0000
refactor breaks -> [minVal, ...breaks] to fix legend bug
- refactor api.fetchBreaks to return a rounded, deduplicated array
combining the breaks with the min value for the current category.
- refactor renderMapViz.getChoropleth color to ignore first
entry in breaks array
- refactor map legend to remove redundant adding of min val to breaks
and subsequen re-rounding / deduplication
These changes needed to fix issue where the min val was only being
removed from the breaks array the legend shows, but not from the
choropleth shading routine, …
> refactor breaks -> [minVal, ...breaks] to fix legend bug

- src/components/Header.svelte
New link added to ons.gov.uk/census from Census 2021 logo.
Co-authored-by: James Trimble <James.Trimble@ons.gov.uk>
read the code, click the links in the preview header and they should take you to the ONS homepage (ons logo) and ONS census page (census logo). 
Anyone
> ONS logo links to ons.gov.uk rather than Census Maps homepage.

- src/data/api.ts
- src/map/renderMapViz.ts
- src/types.ts
- src/util/numberUtil.ts
- there are no ratios in use any more (data comes in as percentages from the s3 files), so replace any reference to 'ratio' with 'percentage' or similar.
- fix some prettier issues
> replace references to ratios with percentage throughout code

- scripts/mktiles/.gitignore
Added mktiles binaries to .gitignore, narrowed scope of other .gitignore entries.
eyeballs
> fix gitignore to ignore binaries

- src/helpers/classificationHelpers.ts
configure all classifications for main_language_detailed for display to two decimal places
> use 2DP for all main_language_detailed classifications

- scripts/atlas-host/docker-compose.yml
The default container logging on the Atlas host is 'syslog'. This changes our containers to 'local' logging.
> use local logging for our atlas containers

- scripts/atlas-host/README.md
Added some info in the Atlas host readme about where to find the terraform and ansible instructions for building the host itself.
> add pointer to docs about building Atlas host with terraform

- src/components/AreaSearch.svelte
- src/components/Select.svelte
- src/helpers/areaSearchHelper.ts
- src/helpers/categoryHelpers.ts.test.ts
[trello ticket](https://trello.com/c/niVljGHB)
commit 0aa7eea0b0caab6b9a37d1250c45f3088e98b08a (HEAD -> feature/162-area-search-ui-tweaks, origin/feature/162-area-search-ui-tweaks)
Date:   Wed Nov 30 13:12:40 2022 +0000
ignore spaces filtering areas search results for display
- ignore spaces when filtering the results of area searches for display
in drop-down box. This is to allow people to search for postcodes without
using spaces.
commit 1d69ea88763b8e5468b17b5f0d54d274c980ce31
Date:   Wed Nov 30 12:55:23 2022 +0000
only show results or loading/no results messages in area search box
- refactor Select component to only show drop-down with results,
loading message or 'no results for x' …
> Feature/162 area search UI tweaks

- scripts/mktiles/cmd/mktiles2/main.go
Make the path to content.json a mktiles2 command line option instead of hardcoding it to "content.json" within the input directory.
> make location of content.json a command line option

- scripts/mktiles/cmd/mktiles2/main.go
- scripts/mktiles/metric2/metric.go
- scripts/mktiles/metric2/metric_test.go
Match "GeographyCode" in metrics files with any spaces and case-insensitively. So, eg, " geography code " will be accepted.
Match the .CSV extension in metrics files case-insensitively. Know to skip msoa-names.csv because it isn't a metrics file.
> match .CSV case-insensitive, fuzzy match "GeographyCode"

- e2e/releases.spec.ts
- src/helpers/classificationHelpers.ts
All SOGI variables should be displayed to 2 decimal places
👀  the code
Check the netlify preview to see if all sogi clasifications (all under identity/gender-identity, identity/sexual-orientation) have two decimal places
Anyone
> display all SOGI classifications with 2dp precision

- scripts/mktiles/metric2/metric.go
some metrics file inputs for the HOU topic have NaNs in them (seems to be in there as 'NA', which might be an excel thing). The correct action for these should be to skip this row but carry on processing the file (it means that the geo for that row will have no data, but thats ok in this case!). Code added here as a quick and dirty patch just to get the data processed - @wavemechanics feel free to polish!
> ignore NaNs in metrics file inputs for mktiles (skip row if found)

- Dockerfile.concourse
- ci/scripts/build.sh
docker image builds weren't working. Following the internets advice added the package-lock.json as well as package.json to the dockerfile. This fixed the builds locally.
> add package-lock.json to docker concourse build to fix npm install

- scripts/content/2021-content-spec.json
- scripts/content/output_content_jsons/2021-ALL.json
- scripts/content/output_content_jsons/2021-ARM.json
- scripts/content/output_content_jsons/2021-DEM.json
- scripts/content/output_content_jsons/2021-EDU.json
- scripts/content/output_content_jsons/2021-EILR.json
- scripts/content/output_content_jsons/2021-HOU.json
- scripts/content/output_content_jsons/2021-HUC.json
- scripts/content/output_content_jsons/2021-LAB.json
- scripts/content/output_content_jsons/2021-MIG.json
- scripts/content/output_content_jsons/2021-SOGI.json
- scripts/content/output_content_jsons/2021-TTW.json
- scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
update content for metadata v38
- 👀 
- go to the preview and check it all looks good - only difference is that the long description for main language detailed has been updated:
- old version: [https://www.ons.gov.uk/census/maps/choropleth/identity/main-language-detailed/main-language-detailed-23a/english-english-or-welsh-if-in-wales](https://www.ons.gov.uk/census/maps/choropleth/identity/main-language-detailed/main-language-detailed-23a/english-english-or-welsh-if-in-wales)
- new version [https://deploy-preview-384--dp-census-atlas.netlify.app/choropleth/identity/main-language-detailed/main-language-detailed-23a/english-english-or-welsh-if-in-wales](https://deploy-preview-384--dp-census-atlas.netlify.app/choropleth/identity/main-language-detailed/main-language-detailed-23a/english-english- …
> update content for metadata v38

- scripts/content/make-florence-zips.sh
tiny fix - the helper script for making florence zips said it was putting the wrong stuff into the wrong zip (behaviour was correct, logging was wrong)
> fix logging messages in content/make-florence-zips.sh

- src/components/EmbedThis.svelte
- src/helpers/embedHelper.ts
- src/helpers/paramsHelper.ts
- src/map/initMap.ts
- src/map/layers.ts
- src/stores/params.ts
commit 9961d0a7f4431a0e793cc43d26556835b3ef9823 (HEAD -> feature/lockable-geotypes-for-embed, origin/feature/lockable-geotypes-for-embed)
Date:   Tue Jan 10 12:38:44 2023 +0000
restrict min zoom to 9 for geoLocked OA only
- When query param geoLock=oa, restrict map min zoom level to 9.
This seems a reasonable compromise between rural and urban areas
when geolocked to OA (when not geolocked the min zoom can be as low
as 8 for OA, but this will only be actually available to the user
in areas with very few OA's on screen at any one time)
commit 22e56c6080bed19c9dc07d362b5a8419b07820be
Date:   Tue Jan 10 10:37:47 2023 +0000
Revert "adjust min zoom for geolevels"
This reverts commit …
> implement simple geolock for embeds

- scripts/content/2021-content-spec.json
- scripts/content/input_metadata_files/classification_available_geotypes.csv
- scripts/content/input_metadata_files/variable_caveats.csv
- scripts/content/output_content_jsons/2021-ALL.json
- scripts/content/output_content_jsons/2021-ARM.json
- scripts/content/output_content_jsons/2021-DEM.json
- scripts/content/output_content_jsons/2021-EDU.json
- scripts/content/output_content_jsons/2021-EILR.json
- scripts/content/output_content_jsons/2021-HOU.json
- scripts/content/output_content_jsons/2021-HUC.json
- scripts/content/output_content_jsons/2021-LAB.json
- scripts/content/output_content_jsons/2021-MIG.json
- scripts/content/output_content_jsons/2021-SOGI.json
- scripts/content/output_content_jsons/2021-TTW.json
- scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
- add custom age-standardised variants of all huc variables
- update available geotypes for non-age-standardised huc variables
- update content to latest metadata v39
- 👀 
- go to 'health' in preview and see how it looks: https://deploy-preview-404--dp-census-atlas.netlify.app/choropleth/health
Anyone
> add age-standardised variants of HUC variables + metadata v39

- scripts/s3sync/cli/cli.go
- scripts/s3sync/storage/location.go
- scripts/s3sync/storage/location_test.go
The bucket:prefix notation for S3 locations causes problems with windows paths which can have a drive letter and colon.
This change uses the aws cli notation for S3 locations: s3://bucket[/prefix]
> use S3 URIs instead of bucket:prefix notation

- scripts/s3sync/storage/s3/s3.go
s3sync wasn't setting the file content type on upload, so the content type on download was always application/octet-stream.
This change sets a content type based on filename extension. Good enough for what we need now.
> include content-type in S3 upload metadata

- README.md
- src/data/api.ts
Switch to the simpler version of the ckmeans json files (smaller, easier to process)
- 👀 
- compare with [original breaks](https://dp-census-atlas.netlify.app) using [the preview below](https://deploy-preview-412--dp-census-atlas.netlify.app), they should be identical. Some random samples for each topic:
- [original arm](https://dp-census-atlas.netlify.app/choropleth/population/uk-armed-forces-veteran-indicator/uk-armed-forces/previously-served-in-uk-reserve-armed-forces?lad=E06000042) vs [new arm](https://deploy-preview-412--dp-census-atlas.netlify.app/choropleth/population/uk-armed-forces-veteran-indicator/uk-armed-forces/previously-served-in-uk-reserve-armed-forces?lad=E06000042)
- [original dem](https://dp-census-atlas.netlify.app/choropleth/population/legal-partnership-status/legal-pa …
> use simplified breaksCkmeans files

- src/helpers/choroplethHelpers.ts
- src/helpers/choroplethHelpers.ts.test.ts
- src/map/renderMapViz.ts
- update choroplethHelpers.getChangeColours to use new 9-point colour scheme
- remove 'noData' colour and associated routine in renderMapViz - no data geos are now default grey in change
> refactor for new 9-point change-over-time colour scale

- src/components/MapLegend.svelte
- src/components/MapLegendExplanation.svelte
- src/helpers/classificationHelpers.ts
- for pop density, the small explanation said ‘people’ but the large unit has always said ‘persons’ - so change Percentage change in people per square kilometres between 2011 and 2021 census. to Percentage change in persons per square kilometre between 2011 and 2021 census. 
- add the variable name to the small explanation. I’ve finally found a way that I think works. This fixes lots of issues. I think it can probably be done without a re-QA because it’s only adding something that is already visible in the nav (namely, the variable name).
> Legend explanation improvements
