src/app.html, src/components/Header.svelte, src/components/Heading.svelte, tailwind.config.cjs
Add basic / rudimentary ONS styling
Visually compare with existing prototype.
Anyone
=> Add basic ONS styling

Dockerfile.concourse, Makefile, ci/audit.yml, ci/build.yml, ci/lint.yml, ci/scripts/audit.sh, ci/scripts/build.sh, ci/scripts/lint.sh, ci/scripts/unit.sh, ci/unit.yml
commit 7583ee711d186c5f3183d05f3d4c4b15c7979a96 (HEAD -> feature/add-ci, origin/feature/add-ci)
Date:   Wed Mar 16 13:55:13 2022 +0000
Add CI skeleton
- Add makefile (proxy for NPM)
- Add node-based dockerfile for deployable images
- Add CI directory with concourse tasks and associated shell scripts
=> Add CI skeleton

src/app.css, src/components/Badge.svelte, src/components/Button.svelte, src/components/CategoryPage.svelte, src/components/CensusPanel.svelte, src/components/Footer.svelte, src/components/Header.svelte, src/components/Heading.svelte, src/components/Layout.svelte, src/components/Map.svelte, src/components/MapKey.svelte, src/components/Navigation.svelte, src/components/PlacesPanel.svelte, src/components/RadioButton.svelte, src/components/RightChevron.svelte, src/components/SearchBox.svelte, src/components/SearchBoxItem.svelte, src/components/TopicList.svelte, src/components/VariablePage.svelte, src/components/tabs/Tab.svelte, src/components/tabs/TabList.svelte, src/helpers/searchCensusHelper.ts, tailwind.config.cjs
Separate Tailwind by the `ts-` prefix.
=> Separate Tailwind

package-lock.json
=> bump minimist 1.2.5 => 1.2.6 (security update)

src/map/initMap.ts
Use the 'move' and 'zoom' events for map updates to improve the responsiveness and fluidity of map viz updates.
Check that it looks good, and that # requests is throttled to one per second.
Anyone
=> Use move and zoom events for map updates

src/components/Heading.svelte
Fix type error and a11y warning in Heading component
run `npm run check` and notice the error and warning have gone
Anyone
=> Fix type error and a11y warning in Heading component

.gitignore, content-csv-to-json/content_csv_to_json.py, content-csv-to-json/test_content_csv_to_json.py, src/components/CategoryHeading.svelte, src/components/CategoryLocationSummary.svelte, src/components/CategoryPage.svelte, src/data/content.ts, src/data/fetchVizData.ts, src/helpers/categoryHelpers.ts, src/helpers/categoryHelpers.ts.test.ts, src/types.ts, src/util/stringUtil.ts
commit 833e70cddfaace1850e75c4f77230caa320a5766 (HEAD -> feat/441-Add-LocationCategorySummary-component, origin/feat/441-Add-LocationCategorySummary-component)
Date:   Fri Mar 25 16:28:59 2022 +0000
add defaultGeoVariableData to vizStore
- refactor fetchVizData.fetchSelectedGeographyData to always
request 'default' geography data (England and Wales) as well
as whatever was requested
- refactor fetchVizData.parseSelectedGeographyData to handle
two rows of input (one for selected geography, one for default
geography)
- add defaultGeoVariableData to vizStore and associated types.
These changes needed to surface the england and wales data
for comparisons displayed on the category page and subcomponents.
commit …
=> Feat/441 add location category summary component + new content.ts (V_3b)

src/components/CategoryLocationSummary.svelte, src/components/SearchHeader.svelte, src/data/fetchGeographyData.ts, src/data/fetchVizData.ts, src/helpers/categoryHelpers.ts, src/helpers/spatialHelper.ts
The default geography will always be England and Wales, so
should be renamed for clarity.
Read the code, check the preview
Anyone
=> rename spatialHelper.defaultGeography -> .englandAndWales

src/components/Header.svelte, tailwind.config.cjs
The ONS logo and "Census Atlas" text title are now hyperlinks to the index page.
=> wraps Census Atlas in hyperlink

src/helpers/locationSelectHelper.ts
=> adds comments to handleLocationSelect fn

.github/workflows/node.js.yml
What
Adds config to run test suite on every push to develop or PR into develop.
How to review
Approve and then we can check if it's working as expected.
Who can review
dev crew
=> sets up yaml file

src/components/TopicList.svelte, src/components/TopicPage.svelte, src/components/TopicsPage.svelte
Sweep of topics page, mainly padding etc.
=> Fix: Style sweep of topics page topics list.

src/components/CategoryLocationSummary.svelte, src/helpers/categoryHelpers.ts, src/helpers/categoryHelpers.ts.test.ts
=> simple % comp for EW in CatLocSummary

.github/workflows/node.js.yml
=> tidy up GA unittests

package.json
Set default localhost port to 28100, to match the port declared in the dp repo
=> use port 28100 for localhost

.eslintrc.json, package-lock.json, package.json, src/components/CategoryPage.svelte, src/map/initMap.ts, src/map/initMapLayers.ts, src/map/layers.ts, src/map/renderMapViz.ts
Add LAD layer to the map
See ticket
Anyone
=> Add LAD layer

dp-census-atlas.nomad
=> add nomad vault policy to nomad conf

Dockerfile.concourse
=> set dockerfile.Concouse port to 28100

Dockerfile.concourse
=> remove port override from dockerfile.Concourse CMD

src/routes/census-atlas.svelte
=> add WIP census-atlas route to allow ONS infrastructure to work

dp-census-atlas.nomad, package.json, src/helpers/buildHyperlinkHelper.ts, src/helpers/buildHyperlinkHelper.ts.test.ts, src/helpers/locationSelectHelper.ts, src/routes/census-atlas.svelte, svelte.config.js, workaround-sveltekit-3726.sh
Workaround for deployment URL.
=> Add base path

ci/scripts/build.sh
Add some stdout to the build.sh CI script to see if it knows what branch (and therefore env) its building.
eyeballs, try the added shell commands locally to check they work for detecting git branch
Anyone
=> POC git branch aware build.sh

ci/scripts/build.sh
=> build.sh prints current git branch

ci/scripts/build.sh
=> PoC - get git details from concourse env in build stage

ci/scripts/build.sh
=> longer sed method for getting current git branch

src/components/CategoryPage.svelte, src/map/initMapLayers.ts, src/map/layers.ts
commit abd69737d54566233e7f2833b4d95bc9abb997ba (HEAD -> feature/add-output-areas, origin/feature/add-output-areas)
Date:   Mon May 9 11:39:49 2022 +0100
add OA map layer, add map layer sourceLayer parameter
- Add new output area map layer to atlas
- As new map tiles have a source-layer name that does not match the
layer name, added specific 'sourceLayer' parameter to layer
defitions in layers.ts, rather than assuming source-layer==layer name
Pull the code locally, npm run preview, zoom in, you should see OA outlines
Anyone
=> add OA map layer, add map layer sourceLayer parameter

src/routes/health.ts
simple logging of incoming health checks
=> simple logging of incoming health checks

dp-census-atlas.nomad, src/routes/health.ts
changed nomad health timeout to 4m as 2m seems to slow...
=> bump nomad health timeout to 4m

src/data/api.ts, src/data/parsers.ts
refactor fetchSelectedGeographyInfo to pul data from s3 geojson instead of geodata API geo endpoint|
=> fetch bbox for currently selected geography from geojson file

README.md
Fix an unsigned Github commit with a small edit to readme.md
=> Fix unsigned commit with small readme edit

README.md
=> Add flat-file API docs

src/helpers/quadsHelper.ts, src/map/initMap.ts, src/map/initMapLayers.ts, src/map/layers.ts, src/map/renderMapViz.ts
Patches @bothness's work on dynamic layer switching . 
Please check and manually test that the map still works as expected. 
Anyone
=> Patch @bothness layer switching

env/dev.sh, env/netlify.sh, env/ons.sh, env/test.sh, src/buildEnv.ts, src/data/api.ts
=> geoBaseUrl from env => hardcoded cdn geoBaseUrl in api.ts

src/data/api.ts
=> update 2021 geos to v1

scripts/content/make_content_jsons.py, scripts/content/output_content_jsons/2021-v2/2021-v2-ALL.json, scripts/content/output_content_jsons/2021-v2/2021-v2-DEM.json, scripts/content/output_content_jsons/2021-v2/2021-v2-EDU.json, scripts/content/output_content_jsons/2021-v2/2021-v2-EILR.json, scripts/content/output_content_jsons/2021-v2/2021-v2-HOU.json, scripts/content/output_content_jsons/2021-v2/2021-v2-HUC.json, scripts/content/output_content_jsons/2021-v2/2021-v2-LAB.json, scripts/content/output_content_jsons/2021-v2/2021-v2-MIG.json, scripts/content/output_content_jsons/2021-v2/2021-v2-SOGI.json, scripts/content/output_content_jsons/2021-v2/2021-v2-TTW.json
=> make available_geotypes in content.json lowercase to match front-end

src/data/api.ts
Remove console (and prettify)
Read PR
Anyone
=> Remove console.log

src/components/Layout.svelte, src/components/OnsAnalyticsBanner.svelte, src/global.d.ts
Patch @bothness's  GTM analytics branch. Needs layout improvements.
Check functionality is working as required in GTM.
@bothness
=> Add analytics

src/components/CategoryPage.svelte, src/components/IntroAndExamples.svelte, src/components/MapLegend.svelte, src/components/VariableGroupPage.svelte, src/components/VariablePage.svelte, src/helpers/buildHyperlinkHelper.ts, src/helpers/buildHyperlinkHelper.ts.test.ts, src/util/numberUtil.ts
Enable multiple classifications!
Ensure all links still work and that you can see multiple classifications for variables that have them.
Anyone
=> Classifications

scripts/content/input_metadata_files/Atlas_variables_short_descriptions.csv
Add short descriptions suitable for the Atlas
Ensure descriptions load and look OK.
Anyone.
=> Add Atlas short descriptions and notes

src/components/App.svelte, src/components/Layout.svelte, src/routes/(app)/+layout.svelte, src/routes/(app)/+page.svelte, src/routes/(app)/choropleth/[variableGroup]/+page.svelte, src/routes/(app)/choropleth/[variableGroup]/[variable]/+page.svelte, src/routes/(app)/choropleth/[variableGroup]/[variable]/[classification]/[category]/+page.svelte, src/routes/(debug)/+layout.svelte, src/routes/(debug)/debug/content/+page.svelte, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/choropleth/[variableGroup]/+page.svelte, src/routes/choropleth/[variableGroup]/[variable]/+page.svelte, src/routes/choropleth/[variableGroup]/[variable]/[classification]/[category]/+page.svelte
Fixes regression introduced in cf2d7ca2153cbdb84953827f4b3f317b35d541c0 that caused the map to re-render on navigation.
Please note that map doesn't re-render on navigation, and that geographies stay in view and selected.
Anyone.
=> Fix map re-render with named layouts

dp-census-atlas.nomad
Add publishing instance management config to dp-census-atlas.nomad.
=> add publishing stanza to dp-census-atlas.nomad

src/data/content.ts
=> use latest 2021 content json (undo accidental overwrite)

scripts/content/output_content_jsons/2021-population-density-median-age.json
add content json for population density and median age
=> add content json for population density and median age

src/data/content.ts
=> add missing config to view dem and mig prod / preview

src/data/setContentStore.ts, src/helpers/contentHelpers.ts
=> lexical sort variables

src/helpers/embedHelper.ts
Fix embed code height at 600px
Check works as expected
Anyone
=> Fix embed code height at 600px

scripts/mktiles/metric2/fake.go
Fake data generated by mktiles2 is supposed to be percentages instead of ratios.
=> mktiles2 fake data generates percentages

src/map/initMap.ts, src/map/initMapLayers.ts, src/map/style.ts
=> Add maxBounds from @bothness map-improvements

package-lock.json, package.json, src/app.css, src/components/CategoryPage.svelte, src/components/ClassificationPager.svelte
Instead of a separate Variable page, view all available classifications (and go straight to them) with a pager. 
Ensure can view multiple classifications easily.
Anyone
=> Add classifications pager

src/components/BreaksChart.svelte, src/components/BreaksMarker.svelte, src/components/MapLegend.svelte, src/data/api.ts, src/helpers/geographyHelper.ts, src/map/initMap.ts, src/stores/flyto.ts, src/stores/selected.ts, src/stores/viz.ts
Solve 'Leeds problem' -- introduce new `selected` store with *data value* for currently selected geo, regardless of current map geoType.
Check no regressions.
Anyone
=> Solve 'Leeds problem' and add ghost marker

src/components/EmbedThis.svelte, src/helpers/embedHelper.ts, src/map/initMap.ts, src/stores/selection.ts
Parameterised embed, support `interactive` param, and add embed preview!
Test the changes.
Anyone
=> Parameterised embed, 'interactive' param, add embed preview

src/components/BreaksChart.svelte, src/components/BreaksMarker.svelte, src/components/VariableDescription.svelte
=> Feature/minor UI tweaks

scripts/content/make_content_jsons.py, scripts/content/output_content_jsons/2021/2021-ALL.json, scripts/content/output_content_jsons/2021/2021-DEM.json, scripts/content/output_content_jsons/2021/2021-EDU.json, scripts/content/output_content_jsons/2021/2021-EILR.json, scripts/content/output_content_jsons/2021/2021-HOU.json, scripts/content/output_content_jsons/2021/2021-HUC.json, scripts/content/output_content_jsons/2021/2021-LAB.json, scripts/content/output_content_jsons/2021/2021-MIG.json, scripts/content/output_content_jsons/2021/2021-SOGI.json, scripts/content/output_content_jsons/2021/2021-TTW.json
=> fix missing apostrophe in resident_age long_desc

src/components/ClassificationPager.svelte
=> Simplify classification pager

src/map/initMap.ts, src/map/layers.ts
=> Fix OA fitBounds bug

src/components/CategoryPageLinks.svelte
=> Update latest download link

src/helpers/choroplethHelpers.ts
=> Use new choropleth palette

src/components/CategoryPageLinks.svelte
=> Revert download link

src/components/CategoryPageLinks.svelte
=> Restore temporary download link

src/data/content.ts
=> use now-public dem/mig data in dev and netlify

src/components/HomePage.svelte, src/components/OnsAnalyticsBanner.svelte, src/components/VariableGroupList.svelte
- Move 'Further topic data' message
- Don't leave a white box under the map on Safari
Ensure no regressions
Anyone
=> Move 'Further topic data' message

src/data/content.ts
=> fix prod content.ts

src/helpers/contentHelpers.ts
Correct initialReleasePeriod check so the examples move when all the topics are released.
Ensure no regressions.
Anyone
=> Correct initialReleasePeriod check

src/data/content.ts
=> fix incorrect fake data url in content.ts

src/data/content.ts
=> actually fix incorrect fake data url in content.ts

src/components/MapLegend.svelte
check the legend works properly in the preview!
=> fix reference to renamed viz property ratioToTotal in MapLegend

src/components/AreaSearch.svelte
=> Add padding to area search empty message

src/map/initMap.ts
=> Fix initial position ordering

src/components/MapLegend.svelte
=> Fix map attribution distraction on sm screen

src/data/content.ts, src/data/content.ts.test.ts
add welsh skills, labour market and travel to work releases to prod pre-pub and prod config
=> add lab, ttw and welsh skills to prepub prod config

src/components/CategorySelector.svelte, src/components/MapLegend.svelte
=> Fix category selector

scripts/mktiles/INPUTS.md, scripts/mktiles/README.md
A little documention on the input files mktiles2 expects to find.
=> add description of mktiles2 input files

README.md
Add release process docs
Read them, but we'll no doubt want to add to them next time we do a release.
Anyone
=> Add release docs

src/app.html, src/components/App.svelte
=> Set min height 570px

scripts/content/2021-content-spec-v33.json
add latest config file for conent. mistakenly missed off
=> check in missing 2021-content-spec-v33.json

package-lock.json, package.json, scripts/postcode-lookup/.gitignore, scripts/postcode-lookup/README.md, scripts/postcode-lookup/mkPostcodeLookup.js, src/components/AreaSearch.svelte, src/helpers/areaSearchHelper.ts, src/types.ts
commit 2b240d7a937cccbd1a6b874e9ac5afc937af977e (HEAD -> feature/self-hosted-postcode-lookup, origin/feature/self-hosted-postcode-lookup)
Date:   Wed Nov 23 15:04:09 2022 +0000
replace postcodes.io with flat file postcode lookups from s3
refactor area search components to use postcode lookup json files
from s3 instead of calling postcodes.io. This change needed to avoid
potential GDPR issues with postcodes.io
commit 5f6731b6fcd081ce8422b5fdd577a618b6da5f96
Date:   Wed Nov 23 15:01:18 2022 +0000
add scripts/postcode-lookup/mkPostcodeLookup.js
Add script for making postcode to OA lookup json from ONS geoportal
Postcode to Postcode Sector to Postcode District to Postcode Area to
2021 Output …
=> postcode lookups from s3 flat files

src/data/setContentStore.ts
=> Set no-cache for content.jsons

e2e/examples.spec.ts, src/components/HomePage.svelte, src/components/LabTtwWelshSkillsExamples.svelte, src/helpers/contentHelpers.ts
update examples for labour market release - trello ticket: https://trello.com/c/XOuzIQ7F
check the preview - you should see `Find out what percentage of people were in employment in East Lindsey` as one of the examples on the home page (and the geography for all examples should update when you select somewhere on the map)
Anyone
=> add LabTtwWelshSkillsExamples and update example e2e tests

src/helpers/categoryHelpers.ts
=> Temporarily fix legend typo

src/data/content.ts
=> fix to sogi and hou urls

README.md
=> Improve release docs

scripts/content/make_content_jsons.py, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
content slugify replace +/- with plus/minus
=> content slugify replace +/- with plus/minus

e2e/examples.spec.ts
=> Simplify examples e2e tests

Dockerfile.concourse, ci/audit.yml, ci/build.yml, ci/component.yml, ci/lint.yml, ci/unit.yml
=> pin node version to 18.x in CI

scripts/content/input_metadata_files/category_legend_strings.csv, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
=> update occupancy_rating legend strs following qa feedback

scripts/content/2021-content-spec.json, scripts/content/input_metadata_files/classification_available_geotypes.csv, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
=> update content to metadata v37

src/data/content.ts, src/data/content.ts.test.ts
Add the upcoming education release to the prod / publishing preview content list
👀  the code (difficult to check results until this merges to master!)
Anyone
=> add edu to prod / publishing preview content

scripts/content/input_metadata_files/classification_data_downloads.csv, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
=> update data download link for has-ever-worked

src/data/content.ts
remove HUC from the prod content list as it got published somehow!
👀 
Anyone
=> TEMP FIX remove huc from prod content as it was accidentally published!

e2e/releases.spec.ts, scripts/content/input_metadata_files/category_legend_strings.csv, scripts/content/input_metadata_files/classification_data_downloads.csv, scripts/content/input_metadata_files/variable_short_descriptions.csv, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
update content to address qa feedback for education
=> update content for edu qa feedback

src/data/content.ts
have to switch to a new visualisation for the huc content json after the old one got published somehow
👀 
Anyone
=> update florence url for huc

src/components/Layout.svelte
=> Fix overflow regression

scripts/content/2021-content-spec.json, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
non-age-standardised huc variables are not yet available, so they need to be removed from the content json until they are!
- 👀 
Anyone
=> remove currently-unavailable non-asp huc variables from content

e2e/releases.spec.ts
=> fix e2e tests for huc

scripts/content/2021-content-spec.json, scripts/content/input_metadata_files/classification_data_downloads.csv, scripts/content/input_metadata_files/variable_short_descriptions.csv, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
trweak some content values following qa feedback
- 👀 
Anyone
=> update HUC content for qa feedback

scripts/content/2021-content-spec.json, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
update content to metadat v40
- 👀 
- 
Anyone
=> update content to metadata v40

src/components/CategoryPage.svelte
=> Dry category link

scripts/content/Pipfile, scripts/content/Pipfile.lock
=> pytest->7.2 to fix security vulnerability

e2e/releases.spec.ts, src/data/content.ts
add huc published content to dev instances
- 👀 
- check the updated e2e passes
Anyone
=> add huc published content to dev instances

src/routes/api/test-proxy/+server.ts
add api/test-proxy endpoint to test feasibility of fetching pre-publication content jsons server-side
👀 
Anyone
=> temp test-proxy endpoint to investigate proxying florence urls with auth

Dockerfile.concourse, ci/audit.yml, ci/build.yml, ci/component.yml, ci/lint.yml, ci/unit.yml, package.json
=> pin playwright version

src/data/content.ts, src/routes/(debug2)/+layout.server.ts, src/routes/(debug2)/+layout.svelte, src/routes/(debug2)/debug2/content/+page.svelte
quick implementation of server-side fetching of content json, used only by the debug/content route. Needs testing in prod publishing
=> add test server-side load of content jsons for debug page only

src/routes/(debug2)/+layout.server.ts
=> add cookie passthrough to test debug ssr page load

src/routes/(debug2)/+layout.server.ts
=> specifically include cookies in test page load

scripts/content/2021-content-spec.json, scripts/content/input_metadata_files/category_legend_strings.csv, scripts/content/input_metadata_files/classification_2011_comparison_data_availability.csv, scripts/content/output_content_jsons/2021-ALL.json, scripts/content/output_content_jsons/2021-ARM.json, scripts/content/output_content_jsons/2021-DEM.json, scripts/content/output_content_jsons/2021-EDU.json, scripts/content/output_content_jsons/2021-EILR.json, scripts/content/output_content_jsons/2021-HOU.json, scripts/content/output_content_jsons/2021-HUC.json, scripts/content/output_content_jsons/2021-LAB.json, scripts/content/output_content_jsons/2021-MIG.json, scripts/content/output_content_jsons/2021-SOGI.json, scripts/content/output_content_jsons/2021-TTW.json, scripts/content/output_content_jsons/2021-WELSH-SKILLS.json
- update content to metadata v43
- fix population in language legend strings to people 3 years+
- fix legend strings for armed forces
- fix issue with change-over-time available geotypes for country of birth and migrant indicator
=> metadata v43 plus content fixes

package-lock.json
=> remove merge conflict marks from package-lock.json

scripts/breaks/cmd/breaks/breaks.go, scripts/breaks/cmd/breaks/breaks_test.go, scripts/breaks/cmd/breaks/main.go, scripts/breaks/cmd/breaks/table.go, scripts/breaks/cmd/breaks/table_test.go, scripts/breaks/go.mod, scripts/breaks/go.sum
new breaks cli to generate breaks files from a directory full of metrics files
=> add breaks cli

README.md
=> Add handover Git info

src/components/CategoryPage.svelte, src/components/ClassificationPager.svelte, src/components/OtherModeLinks.svelte, src/helpers/contentHelpers.ts
=> Fix navigation for change over time

scripts/content/README.md
=> update content scripts readme

scripts/mktiles/mktiles2.mandoc
Fixed some typos I noticed while putting together mktiles2 demo.
=> minor fixes to mktiles2.mandoc

README.md, src/components/MapControls.svelte, src/components/MapLegendExplanation.svelte, src/data/staticContentJsons/2021-MASTER.json, src/helpers/contentHelpers.ts, src/helpers/contentHelpers.ts.test.ts, src/stores/selected.ts, src/stores/viz.ts
=> Post-change tweaks

src/components/CategoryPage.svelte, src/helpers/contentHelpers.ts
Tidy category page - move helper to helper file
No regressions
Anyone
=> Tidy category page - move helper to helper file

scripts/mkess/cmd/mkess/content.go, scripts/mkess/cmd/mkess/indicator.go, scripts/mkess/cmd/mkess/main.go, scripts/mkess/cmd/mkess/zapspecial.go, scripts/mkess/go.mod, scripts/mkess/go.sum
Initial cli to generate data tiles and ess_content.json from metrics spreadsheet.
The generated files are meant to go with the hacked ESS version of Census Maps in spike/ess-data.
You could build the cli:
cd scripts/mkess
go build ./cmd/mkess/...
=> initial mkess cli

scripts/content/input_metadata_files/classification_data_available_geotypes.csv, src/data/staticContentJsons/2021-MASTER.json
Added new geotypes to county_of_birth_4a for choropleth in content.json
=> added msoa and oa to cob-4a classification

dp-census-atlas.nomad
As per title.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.
=> Ensure deployments spread over availability zones

package-lock.json
npm audit fix
Smoke tests
Anyone
=> Update packages for vulnerabilities
